#!/bin/bash

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"


# EXIT
function ctrl_c() {
        echo -e "\n\n${redColour}[!] Exiting...${endColour}"
        exit 0
}
trap ctrl_c INT

if [ $# -ne 1 ]; then
	echo -e "${redColour}[!] Give me the directory for save .tar. example: ./log-archive /tmp${endColour}"
	exit 1
fi

name="logs_archive_$(date +%Y%m%d_%H%M%S).tar.gz"
if [[ ${1:-1} == "\/" ]]; then
	dir=${1:-1}
else
	dir="$1"
fi
mkdir -p "$dir"
tar -cvzf "${dir}/$name" /var/log
